language: rust
rust:
  - nightly
os: linux
dist: bionic

install:
  - rustup component add rust-src
  - cargo install cargo-xbuild llvm-tools-preview bootimage

script:
  - cargo xbuild --verbose --all
  # - cargo xtest --verbose --all
