language: c
os: linux
dist: bionic
compiler: gcc

before_install:
  - sudo apt update
  - sudo apt -y install build-essential bison flex libgmp3-dev libmpc-dev libmpfr-dev texinfo libcloog-isl-dev libisl-0.18-dev wget

install:
  - cd ${TRAVIS_BUILD_DIR}
  - wget https://ftp.wayne.edu/gnu/binutils/binutils-2.34.tar.gz
  - wget https://ftp.gnu.org/gnu/gcc/gcc-9.2.0/gcc-9.2.0.tar.gz
  - tar -xf binutils-2.34.tar.gz
  - cd binutils-2.34
  - mkdir build && cd build
  - ../configure --target=$TARGET --prefix="$PREFIX" --with-sysroot --disable-nls --disable-werror
  - make -j3
  - make install
  - cd ../..
  - tar -xf gcc-9.2.0.tar.gz
  - cd gcc-9.2.0
  - mkdir build
  - cd build
  - ../configure --target=$TARGET --prefix="$PREFIX" --disable-nls --enable-languages=c,c++ --without-headers
  - make all-gcc -j3
  - make all-target-libgcc -j3
  - make install-gcc -j3
  - make install-target-libgcc -j3
  - $HOME/opt/cross/bin/$TARGET-gcc --version
  - cd $HOME
  - tar -cf cross.tar.gz opt

script:
  - cd ${TRAVIS_BUILD_DIR}
  - ./build.py

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: $HOME/cross.tar.gz
  skip_cleanup: true
  draft: true

