[unstable]
build-std = ["core", "alloc"]
build-std-features = ["compiler-builtins-mem"]

[build]
target = "x86_64-unknown-spinel_kernel.json"

[target.'cfg(target_os = "none")']
runner = "bootimage runner"
